name: PBKDF2Js
on:
  push:
    branches:
      - main
jobs:
  unit-test:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up version 20.11.0
        uses: actions/setup-node@v1
        with:
          node-version: 20.11.0

      - name: Install dependencies
        run: npm i

      - name: Test
        run: npm run test  --if-present

      - name: Lint check
        run: npm run link  --if-present

      - name: Build package
        run: npm run build  --if-present

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
