name: publish
on:
  workflow_run:
    workflows: ['Create Release']
    types:
      - completed
# on:
#   release:
#     types: [created]
jobs:
  publish:
    # if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Node.js setup 20.11.0
        uses: actions/setup-node@v1
        with:
          node-version: 20.11.0
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm i

      - name: Test
        run: npm run test  --if-present

      - name: Lint check
        run: npm run link  --if-present

      - name: Build package
        run: npm run build  --if-present

      - name: Publish package
        run: npm publish ./dist --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PBKDF2_SECRET }}
