name: Create Release
on:
  push:
    tags:
      - 'v*' 
jobs:
  release-tag:    
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:  
      - name: Set up                         
        uses: actions/checkout@main
      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: 16          
      - name: Install dependencies
        run: npm i
      - name: Test
        run: npm run test
      - name: Build package
        run: npm run build 
      - name: list files
        run: ls         
      - name: Checkout code        
        uses: actions/checkout@master
      - name: Create Release for Tag
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Please refer to the [README](https://github.com/xkid1/pbkdf2.js/blob/main/README.md) for details.
          draft: false
          prerelease: false



