name: Create Release
on:
  push:
    tags:
      - 'v*' 
jobs:
  release-tag:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code        
        uses: actions/checkout@main
      - name: Create Release for Tag
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PBKDF2_RELEASE }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Please refer to the [README](https://github.com/xkid1/pbkdf2.js/blob/main/README.md) for details.
          draft: false
          prerelease: false